---
# handlers file for common_kubernetes
- name: cargar firewall
  service:
    name: firewalld
    state: reloaded

- name: reinicio_sys
  sysctl:
    name: "{{ item }}"
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward

- name: reinicio
  reboot: