---
#https://docs.ansible.com/ansible/2.9/modules/service_module.html#service-module
- name: iniciar el servicio NFS
  service:
    name: nfs-server
    state: started
    enabled: yes
  tags: nfs
#https://docs.ansible.com/ansible/2.9/modules/file_module.html#file-module
- name: creación directorio NFS
  file:
    path: /mnt/nfs
    state: directory
    owner: 'nobody'
    group: 'nobody'
    mode: '0777'
  tags: nfs

- name: Se añade el fichero exports con la conf de los directorios utilizando template
  template:
    src: exports.j2
    dest: /etc/exports
  notify: exportfs
  tags: nfs