---
# tasks file for common_kubernetes
# Se fraccionan los tasks para facilitar el testeo y no tener que
# pasar todo
- import_tasks: 1-nfs-cliente.yml
- import_tasks: 2-firewall.yml
- import_tasks: 3-instalar-k8s.yml