---
# https://docs.ansible.com/ansible/2.9/modules/k8s_module.html#k8s-module
- name: crear volumen persistente
  k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: nfs-pv
        namespace: apache
      spec:
        capacity:
          storage: 10Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteMany
        persistentVolumeReclaimPolicy: Recycle
        storageClassName: nfs
        mountOptions:
          - hard
          - nfsvers=4.1
        nfs:
          path: /mnt/nfs
          server: vm-nfs
  tags: app