---
# https://docs.ansible.com/ansible/2.9/modules/k8s_module.html#k8s-module
- name: crear llamada volumen persistente
  k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: nfs-pvc
        namespace: apache
      spec:
        storageClassName: nfs
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 2Gi
  tags: app