---
# tasks file for app
- name: create namespace
  k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: nginx
        labels:
          app: nginx
  tags: app

- name: create pod
  k8s:
    definition:
      apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
      kind: Deployment
      metadata:
        name: nginx-deployment
        namespace: nginx
        labels:
          app: nginx
      spec:
        selector:
          matchLabels:
            app: nginx
        replicas: 2 # indica al controlador que ejecute 2 pods
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: mcr.microsoft.com/mcr/hello-world:v1.0
              ports:
              - containerPort: 80
              volumeMounts:
              - name: mnt-nfs
                mountPath: /mnt/nfs
            volumes:
            - name: mnt-nfs
              persistentVolumeClaim:
                claimName: nfs-volume
          tags: app

- name: create service
  k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: nginx-service
        namespace: nginx
      spec:
        selector:
          app: nginx
        ports:
          - name: http
            protocol: TCP
            port: 9090
            targetPort: 8080
  tags: app

- name: create ingress
  k8s:
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: nginx-ingress
        namespace: nginx
        labels:
          app: nginx
        annotations:
          haproxy.org/path-rewrite: "/"
          kubernetes.io/ingress.class: haproxy
      spec:
        rules:
        - http:
            paths:
            - path: /volumes
              pathType: Prefix
              backend:
                service:
                  name: nginx-service
                  port:
                    number: 9090
    tags: app

- name: create configmap
  k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: haproxy-configmap
        namespace: nginx
      data:
        scale-server-slots: "42"
        ssl-redirect: "OFF"
  tags: app