---
# tasks file for app
# Se fraccionan los tasks para facilitar el testeo y no tener que
# pasar todo
- import_tasks: 1-namespace.yml
- import_tasks: 2-pv.yml
- import_tasks: 3-pvc.yml
- import_tasks: 4-deployment.yml
- import_tasks: 5-service.yml
- import_tasks: 6-ingress.yml
- import_tasks: 7-configmap.yml