---
# handlers file for common_kubernetes
# https://docs.ansible.com/ansible/2.9/modules/service_module.html#service-module
- name: cargar firewall
  service:
    name: firewalld
    state: reloaded

- name: reinicio
  reboot: